#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

# debug
# set -x
 
#loads VERSION, DEPS_PARAMS, ID, LOG_FILE, PLAY_COMMAND="${OPENSHIFT_DATA_DIR}play-${VERSION}/play"
. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

if [[ ! $? -eq 0 ]]; then
	exit $?
fi

if [[ ! -f $PLAY_COMMAND ]]; then
	echo "Error: couldn't find play executable at $PLAY_COMMAND" >> $LOG_FILE
	exit 1
fi

cd "$OPENSHIFT_REPO_DIR"

## stop play application
${OPENSHIFT_REPO_DIR}.openshift/action_hooks/stop

if [[ ! $? -eq 0 ]]; then
	echo "Error: could not stop play application" >> $LOG_FILE
	exit 1
fi

export PLAY_LOG_PATH=${OPENSHIFT_LOG_DIR}

# clean everything, compile and stage
# APP_COMMAND="$PLAY_COMMAND clean-all clean stage"
APP_COMMAND="$PLAY_COMMAND stage"

echo "[exec] $APP_COMMAND" >> $LOG_FILE
$APP_COMMAND &>> $LOG_FILE

APP_COMMAND="target/start $PLAY_PARAMS "\
"-Dhttp.port=${OPENSHIFT_INTERNAL_PORT} "\
"-Dhttp.address=${OPENSHIFT_INTERNAL_IP} "\
"-Dconfig.resource=openshift.conf"

echo "[exec] $APP_COMMAND" >> $LOG_FILE
nohup bash -c "$APP_COMMAND &>> $LOG_FILE" &> /dev/null &

# $APP_COMMAND &

if [[ ! $? -eq 0 ]]; then
	echo "Error: starting play application" >> $LOG_FILE
	echo "Error executing '$APP_COMMAND'" >> $LOG_FILE
	exit 1
fi

exit 0
