#!/bin/bash
# The logic to stop your application should be put in this script.

# debug
# set -x

function kill_app {

	command=$1

	# try 5 times to kill it
	for c in `seq 1 5`; do
		echo "Trying to kill proccess, attemp number $c" > $LOG_FILE
		bash -c "$COMMAND &> $LOG_FILE" &> /dev/null
		sleep $c
		#killed it
		if [[ -z `ps -A | grep java` ]]; then
			if [[ -f "RUNNING_PID" ]]; then
				rm RUNNING_PID
			fi
			exit 0
		fi
	done

}

#loads VERSION, DEPS_PARAMS, ID, LOG_FILE, PLAY_COMMAND="${OPENSHIFT_DATA_DIR}play-${VERSION}/play"
. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

if [[ ! $? -eq 0 ]]; then
	exit $?
fi

cd "$OPENSHIFT_REPO_DIR"

#kill play if it was running
if [[ -f "RUNNING_PID" ]]; then

	pid=`cat RUNNING_PID`

	echo "Stopping play application" > $LOG_FILE
	bash -c "$PLAY_COMMAND stop &> $LOG_FILE" &> /dev/null

	if [[ -n $pid ]]; then
		#try to kill it nicely
		kill_app "kill -SIGTERM $pid"

		#try to kill it harshly
		kill_app "kill -SIGKILL $pid"
	fi
fi

#it survived, try to kill it manually
if [[ -n `ps -A | grep java` ]]; then

	#try to kill it nicely
	kill_app "pkill -SIGTERM java"

	#try to kill it harshly
	kill_app "pkill -SIGKILL java"
fi

#couldn't kill it
if [[ -n `ps -A | grep java` ]]; then
	echo "Error: could not stop play application, error executing 'pkill java'" > $LOG_FILE
	exit 1
fi

exit 0